---
odbc_dir: /etc/odbc.ini
odbcinst_dir: /etc/odbcinst.ini
cloudera_impala_odbc_dir: /opt/cloudera/impalaodbc/lib/64/cloudera.impalaodbc.ini
cloudera_hive_odbc_dir: /opt/cloudera/hiveodbc/lib/64/cloudera.hiveodbc.ini

# Application vars:
sasl_url: "https://github.com/cyrusimap/cyrus-sasl/releases/download/cyrus-sasl-2.1.27/cyrus-sasl-2.1.27.tar.gz"
# [Hive]
hive_rpm: 'ClouderaHiveODBC-2.6.11.1011-1.x86_64.rpm'
hive_url_rpm: "https://downloads.cloudera.com/connectors/Cloudera_Hive_ODBC_2.6.11/Linux/{{ hive_rpm }}"
# [Impala]
impala_rpm: 'ClouderaImpalaODBC-2.6.14.1016-1.x86_64.rpm'
impala_url_rpm: "https://downloads.cloudera.com/connectors/impala_odbc_2.6.14.1016/Linux/{{ impala_rpm }}"
# [Snowflake]
snowflake_rpm: 'snowflake-odbc'
snowflake_repo: '/etc/yum.repos.d/snowflake-odbc.repo'
# [mySQL]
mysql_rpm: 'mysql-connector-odbc'